package com.redhat.weightwatcher;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
public class Fact implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Fact ID")
   private int factid;
   @org.kie.api.definition.type.Label("Fact Type")
   private int facttype;
   @org.kie.api.definition.type.Label("Fact Text")
   private java.lang.String facttxt;

   @org.kie.api.definition.type.Label(value = "Fact Name")
   private java.lang.String factname;

   @org.kie.api.definition.type.Label(value = "Fact JSON")
   private java.lang.String factjson;

   public Fact()
   {
   }

   public int getFactid()
   {
      return this.factid;
   }

   public void setFactid(int factid)
   {
      this.factid = factid;
   }

   public int getFacttype()
   {
      return this.facttype;
   }

   public void setFacttype(int facttype)
   {
      this.facttype = facttype;
   }

   public java.lang.String getFacttxt()
   {
      return this.facttxt;
   }

   public void setFacttxt(java.lang.String facttxt)
   {
      this.facttxt = facttxt;
   }

   public java.lang.String getFactname()
   {
      return this.factname;
   }

   public void setFactname(java.lang.String factname)
   {
      this.factname = factname;
   }

   public java.lang.String getFactjson()
   {
      return this.factjson;
   }

   public void setFactjson(java.lang.String factjson)
   {
      this.factjson = factjson;
   }

   public Fact(int factid, int facttype, java.lang.String facttxt,
         java.lang.String factname, java.lang.String factjson)
   {
      this.factid = factid;
      this.facttype = facttype;
      this.facttxt = facttxt;
      this.factname = factname;
      this.factjson = factjson;
   }

}
