package com.redhat.weightwatcher;

import org.json.JSONObject;
import com.redhat.weightwatcher.Goal;

rule "ruleInsertGoal"
	salience 10000
when
    	fact : Fact( factname == "Goal" )
then
        JSONObject factjson = new JSONObject( fact.getFactjson( ).toString( ) );

        Integer userid = new Integer( Integer.parseInt( factjson.get("userid").toString( ) ) );
       	String goalname = new String( factjson.get("goalname").toString( )  );
        Integer target = new Integer( Integer.parseInt( factjson.get("target").toString( ) ) );
        Integer start = new Integer( Integer.parseInt( factjson.get("start").toString( ) ) );
        Integer low = new Integer( Integer.parseInt( factjson.get("low").toString( ) ) );
        Integer high = new Integer( Integer.parseInt( factjson.get("high").toString( ) ) );

    	Goal goal = new Goal(  );
	    goal.setUserid( userid );
	    goal.setGoalname( goalname );
	    goal.setTarget( target );
	    goal.setStart( start );
	    goal.setLow( low );

    	insert( goal );

    	System.out.println("==>weightwatcher " + drools.getRule( ).getName( ) + "->" + 
					goal.getUserid( )  + ":" + goal.getGoalname( ) );
end

query "getGoal"
	goal : Goal( )
end

