package com.redhat.weightwatcher;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Participant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("User ID")
   private int userid;

   @org.kie.api.definition.type.Label(value = "User Name")
   private java.lang.String username;

   public Participant()
   {
   }

   public int getUserid()
   {
      return this.userid;
   }

   public void setUserid(int userid)
   {
      this.userid = userid;
   }

   public java.lang.String getUsername()
   {
      return this.username;
   }

   public void setUsername(java.lang.String username)
   {
      this.username = username;
   }

   public Participant(int userid, java.lang.String username)
   {
      this.userid = userid;
      this.username = username;
   }

}
